name: myfirstaction
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Print "Name"
        run: echo "Hello ${{ vars.MY_NAME }}"
      - name: Print Surname
  surname:
    runs-on: ubuntu-latest
    steps:
      - name : Surname
        run: echo "Surname ${{ secrets.MY_SURNAME }}"
